# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentyard" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "43a62edf601f8709d2621212070dced05e259e90251f503d87b3632ad5126c26"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.4.1/agentyard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "374e53cd253cb461da4376834f448da28de34f4ce80443ce20bcbf52f03ab949"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.4.1/agentyard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4fef6214774e44470fa0e7b2b4bd3cdcd7f6339e10c9c88c9e6bc855f9d3d2b2"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.4.1/agentyard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad7fc31c1e55239a07323995a674a0173fbf790f1f682a398c5e28c824271b8a"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.4.1/agentyard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentyard"
  desc "The yard where your coding agents work: every worktree, PR and agent session on one calm page"
  homepage "https://github.com/MilosMosovsky/agentyard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentyard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentyard"]
    end
  end

  zap launchctl: [
      "com.github.milosmosovsky.agentyard",
    ],
    trash: [
      "~/Library/LaunchAgents/com.github.milosmosovsky.agentyard.plist",
      "~/Library/Caches/agentyard",
      "~/Library/Logs/agentyard.log",
    ]

  caveats <<~EOS
    Start agentyard in the background (asks before changing anything):

      agentyard install

    Or just try it on sample data:

      agentyard demo

    Before removing it, stop the background agent first:

      agentyard uninstall && brew uninstall agentyard

    (or: brew uninstall --zap agentyard)
  EOS
end
