# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentyard" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "f033b961a9979e3f618fbf45f638e44cfad2ff4768373493a81266fb1dd08eb4"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.6.0/agentyard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d2c9f422c7c760c625fab9b3f3e6983afaa3e1c5ac8906d23c055fc9e16dda4"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.6.0/agentyard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7450366509b929794bb6e750c58b6076a264bedaa393a0f01fd5bb33cb9b9ea2"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.6.0/agentyard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "510bc1518c85d61472686a3b711dc77a67dccc256b441132b6da476b00568eaf"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.6.0/agentyard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentyard"
  desc "The yard where your coding agents work: every worktree, PR and agent session on one calm page"
  homepage "https://github.com/MilosMosovsky/agentyard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentyard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentyard"]
    end
  end

  zap launchctl: [
      "com.github.milosmosovsky.agentyard",
    ],
    trash: [
      "~/Library/LaunchAgents/com.github.milosmosovsky.agentyard.plist",
      "~/Library/Caches/agentyard",
      "~/Library/Logs/agentyard.log",
    ]

  caveats <<~EOS
    Start agentyard in the background (asks before changing anything):

      agentyard install

    Or just try it on sample data:

      agentyard demo

    Before removing it, stop the background agent first:

      agentyard uninstall && brew uninstall agentyard

    (or: brew uninstall --zap agentyard)
  EOS
end
