# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentyard" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "dd3f52764a5e83b665621efdee9d9807e50ce15045cd7b263c2e287b020b1fb5"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.5.0/agentyard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "27a7bcf6e22233b05e0ae273c7724bdba69f7e122efdee811b12ec5f5b650e80"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.5.0/agentyard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f09fc5d38df2951c524c6e7a0e925b50a8c6aa783757f5de45fae95e00c9b23d"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.5.0/agentyard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b35b608578dddbfd2147313e680b237a679ab6674f9a917cd31efc3b2cfe0ea5"
      url "https://github.com/MilosMosovsky/agentyard/releases/download/v0.5.0/agentyard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentyard"
  desc "The yard where your coding agents work: every worktree, PR and agent session on one calm page"
  homepage "https://github.com/MilosMosovsky/agentyard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentyard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentyard"]
    end
  end

  zap launchctl: [
      "com.github.milosmosovsky.agentyard",
    ],
    trash: [
      "~/Library/LaunchAgents/com.github.milosmosovsky.agentyard.plist",
      "~/Library/Caches/agentyard",
      "~/Library/Logs/agentyard.log",
    ]

  caveats <<~EOS
    Start agentyard in the background (asks before changing anything):

      agentyard install

    Or just try it on sample data:

      agentyard demo

    Before removing it, stop the background agent first:

      agentyard uninstall && brew uninstall agentyard

    (or: brew uninstall --zap agentyard)
  EOS
end
